import { FC, PropsWithChildren, useEffect, useState } from "react";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";

import cn from "classnames";

import s from "./Layout.module.scss";

const inter = Inter({ subsets: ["latin"] });

const Layout: FC<PropsWithChildren> = ({ children }) => {
  const { isReady: routerReady } = useRouter();
  const [isReady, setIsReady] = useState(false);

  useEffect(() => setIsReady(true), [routerReady]);

  if (!isReady) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cn(s.root, inter.className)}>{children}</main>
    </>
  );
};

export default Layout;
